services:
  mcp-proxy:
    build:
      context: .
      dockerfile: mcp-proxy.Dockerfile
    container_name: mcp-proxy-duckduckgo
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: >
      --port=8080
      --host=0.0.0.0
      --pass-environment
      --allow-origin="*"
      uvx mcp-server-duckduckgo
    environment:
      - UV_PYTHON_PREFERENCE=only-system
      - UV_CACHE_DIR=/tmp/uv-cache
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE